### ISSUE TITLE
Should we skip Empty Comments in aggregation String?

### ISSUE THREAD

**Issue by AndrewRest** [mifort-org/mifort-timesheet#120]
If comments is empty it looks like: ,,,,,,,,,,,,,,
Should we use the placeholder: <empty>,<empty>, <empty>
or just skip it?

**Comment by altrofimov** [comment]
Fixed: now agreagated comment

"4, 34343, , 2222, s"

becomes

"4, 34343, 2222, s"

**Comment by altrofimov** [comment]
I think we should do it

**Comment by AndrewRest** [comment]
Doesn't work for UI 
![image](https://cloud.githubusercontent.com/assets/12434689/13474121/c25408dc-e0cd-11e5-9a50-45b9f17ffe23.png)
