### ISSUE TITLE
Landing Page Issue in IE 10

### ISSUE THREAD

**Issue by sarvaratchgan** [mifort-org/mifort-timesheet#139]
Landing page doesn't load properly. It's taking too long time and its continuously loading 
![injector error](https://cloud.githubusercontent.com/assets/7565739/13696207/c78528d6-e78a-11e5-8c74-b48f367dbdc8.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/7565739/13696208/c78a075c-e78a-11e5-920a-b93cb04503c8.png)

**Comment by altrofimov** [comment]
@sarvaratchgan can't reproduce, could you please try to test one more time?

**Comment by sarvaratchgan** [comment]
Yes. Its working fine now :+1:
