### ISSUE TITLE
Filtering control should select item when user clicks on label not only checkbox 

### ISSUE THREAD

**Issue by AlexKolonitsky** [mifort-org/mifort-timesheet#147]
I guess we can do following behavior:
1) when you click on label - we think that it everything that you want to choose and close control with only this item selected 
2) when you click on checkbox directly you probably want choose several items -> we will not close filter until you do it explicitly

**Comment by altrofimov** [comment]
I agree about the title. And disagree about the body, i suggest to make all the component to behave as they behave everywhere. Not to make user trying to understand why click on label is not the same as click on checkbox as on all the other websites.
