### ISSUE TITLE
Meeting / Project Discussion Invitation

### ISSUE THREAD

**Issue by sarvaratchagan** [mifort-org/mifort-timesheet#154]
Is there any option to invite people for weekly and monthly discussion like google calendar?

**Comment by altrofimov** [comment]
@sarvaratchgan You mean to use the google invitations to ass to Timesheets or you want to have a discussion with us?

**Comment by sarvaratchgan** [comment]
**@altrofimov** I need to use google calendar from timesheet for invite people weekly and monthly discussion. If there is any option I can use that without gmail login.
