### ISSUE TITLE
Should we mark archived project in Report page?

### ISSUE THREAD

**Issue by AnnaFilkova** [mifort-org/mifort-timesheet#157]
![screenshot_1](https://cloud.githubusercontent.com/assets/14108126/13917669/55fb4240-ef73-11e5-93ed-28e503046243.png)

**Comment by altrofimov** [comment]
@AnnaFilkova please make a design of how to mark them

**Comment by altrofimov** [comment]
@AndrewRest please provide the object {name: 'projectName', archived: true} for project filter in 
$http.get('api/v1/report/filters/' + companyId);

**Comment by AndrewRest** [comment]
Changed. New format:
{
   "field": "project",
   "value": [
       {
           "name": "Bla",
           "active": true
       },
       {
           "name": "Fdsfdfsdf",
           "active": true
       }]
  }

https://github.com/mifort-org/mifort-timesheet/wiki/Report-API#get-filter-values-for-common-report

Be carefull that only Get mehod was changed. Common report API is not changed.

**Comment by AndrewRest** [comment]
Need Client side support before the next Deploy
