### ISSUE TITLE
Aggregation period

### ISSUE THREAD

**Issue by AnnaFilkova** [mifort-org/mifort-timesheet#168]
![screenshot_1](https://cloud.githubusercontent.com/assets/14108126/14103341/5594d1a0-f5a8-11e5-84ff-c669b3a62b5b.jpg)

**Comment by altrofimov** [comment]
@AnnaFilkova I'm afraid we cant split this field into two: used library for datepicker use single field, PLUS both of these fields will open the SAME datepicker popup, so it could be strange.

**Comment by altrofimov** [comment]
Try to change - to .
