### ISSUE TITLE
comment saved from previous day type 

### ISSUE THREAD

**Issue by AlexKolonitsky** [mifort-org/mifort-timesheet#186]
Satarday daytype was changed from "Weekend" to working day ('none' day type) but comment in timesheet still be the same "Weekend ".  

![default](https://cloud.githubusercontent.com/assets/947428/14319061/5e5d31c6-fc18-11e5-836f-ac63c8724e95.PNG)

**Comment by altrofimov** [comment]
@AlexKolonitsky need more detailed info.
