### ISSUE TITLE
Annoying notification “Changes saved”

### ISSUE THREAD

**Issue by katerina1v** [mifort-org/mifort-timesheet#265]
Notification “Changes saved” on the bottom right corner is very annoying. It appears after each letter is typed in comments on Timesheet Page.

**Comment by DanilchukV** [comment]
![vsplyivayuschie okna_500x268](https://cloud.githubusercontent.com/assets/26150007/24822736/d41e2e06-1bf7-11e7-870e-a5c224f34503.png)
