### ISSUE TITLE
Name filter doen't work

### ISSUE THREAD

**Issue by AlexKolonitsky** [mifort-org/mifort-timesheet#266]
![2017-02-20_20h49_14](https://cloud.githubusercontent.com/assets/947428/23137816/464a404e-f7b5-11e6-9225-df24fb6fd632.png)

**Comment by JaneKamneva** [comment]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04
Specification: this case is urgent for "Report" tab, fields "Project Name" and "Employee Name"
