### ISSUE TITLE
Projects screen corrupted when I am resizing window 

### ISSUE THREAD

**Issue by AlexKolonitsky** [mifort-org/mifort-timesheet#267]
![2017-02-20_21h01_57](https://cloud.githubusercontent.com/assets/947428/23137922/d7a4eea4-f7b5-11e6-8424-cad94cd60bdc.png)

**Comment by Tima4uk** [comment]
if they make the entire width of the block?

**Comment by Tima4uk** [comment]
won't fix went redisign
