### ISSUE TITLE
Wrong font size when page width 845px

### ISSUE THREAD

**Issue by AlexKolonitsky** [mifort-org/mifort-timesheet#275]
![2017-02-20_22h47_34](https://cloud.githubusercontent.com/assets/947428/23140011/56ebf428-f7c0-11e6-9347-447bc79c5afa.png)

**Comment by AlexDormash** [comment]
everything works

**Comment by NadiaKolonitskaya** [comment]
reproduced at production 
Chrome 60.0.3112.101, window width 845px
![2017-08-26_23h02_38](https://user-images.githubusercontent.com/31158262/29744686-de9d3596-8ab2-11e7-9391-dde738c6304b.png)

**Comment by anabenko** [comment]
FF 55.0.3
Dev - fixed.
