### ISSUE TITLE
Permission Issue

### ISSUE THREAD

**Issue by sarvaratchagan** [mifort-org/mifort-timesheet#279]
When I log in into the portal. I'm getting issues like "You have no permission".

 Please refer the screenshot

Screen shot - 1 :

![image](https://cloud.githubusercontent.com/assets/7565739/23218801/32f71708-f943-11e6-9502-10f3c7a725a9.png)

Screen shot - 2 :

![image](https://cloud.githubusercontent.com/assets/7565739/23218891/87f5062a-f943-11e6-93fe-d68d4f262deb.png)

**Comment by altrofimov** [comment]
REST https://timesheet.mifort.org/api/v1/project/list?companyId=5687a779df8770110048980e should not be triggered on page refrest BEFORE get user REST. 

If you logout and login again via google that that REST is not triggered.

**Comment by sarvaratchagan** [comment]
![image](https://user-images.githubusercontent.com/7565739/28790527-1b7ec752-7647-11e7-9ade-78eccfc64aaa.png)

Still Im seeing same issue

**Comment by NickBerilov** [comment]
Wasn't able to reproduce, closing until there's a reliable way to do that

**Comment by anabenko** [comment]
ff 55.0.3 win7
role: employee
dev/prod

No message displayed.  Fixed.
