### ISSUE TITLE
Timesheet: Forbid negative Time value inserting

### ISSUE THREAD

**Issue by finDer0** [mifort-org/mifort-timesheet#281]
Windows 8.1 Professional; Opera 43.0.2442.806; FF 48.0; IE 11.0.9600.17416

**Steps:**
1. Click on field "Time, h";
2. Paste in field value (Ctrl+V), for example "-1".

**Result:**
![bug 3](https://cloud.githubusercontent.com/assets/25868211/23229295/d6179c5c-f950-11e6-83ce-38bdbd20c423.PNG)

**Expected result:**
Forbid to insert negative values from the clipboard.

**Comment by AlexKolonitsky** [comment]
Add JS validation on the client side for the hours and comment columns. We should highlight incorrect values (negative values and values more then 24h, comment loneger then 500 characters) and notify user but all user input should be saved to DB, accepted by server side and reflected in total.
