### ISSUE TITLE
Timesheet: Limit decimal places in Time field

### ISSUE THREAD

**Issue by finDer0** [mifort-org/mifort-timesheet#282]
Windows 8.1 Professional; Opera 43.0.2442.806; FF 48.0; IE 11.0.9600.17416

**Steps:**
1. Click on field "Time, h";
2. Enter a real number. For example: "0.9999".

**Result:** "Total" is incorrect. ER: 2 decimal places.
![bug 4](https://cloud.githubusercontent.com/assets/25868211/23230839/82ad7ac2-f956-11e6-9729-fb07b871a366.PNG)

**Expected result:** 
Must be "Total" = 6.0999
Rounding numbers at once (after entering).

**Comment by JaneKamneva** [comment]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04
Accurate definition: in the "Timesheet table", field "Time" user can see only two numbers after point. But problem that if you enter 2.999 => in the "time" field you will see 2.99 and in total: 3.00 
![selection_018](https://user-images.githubusercontent.com/26093980/28072358-6531a618-665b-11e7-9fa1-6fb7d016ed71.png)

**Comment by AlexDormash** [comment]
Two numbers of this limit
sum fixed
