### ISSUE TITLE
Impossible to login as user with not gmail domain email

### ISSUE THREAD

**Issue by finDer0** [mifort-org/mifort-timesheet#283]
Windows 8.1 Professional; Opera 43.0.2442.806; FF 48.0; IE 11.0.9600.17416

**Step:**
1. Create email:
    For employee: **tut.by** (**mail.ru**); for owner: **gmail.com**.
2. Log in as owner;
3. Open tab "Company" and invite employees: 
3.1. Input in textbox email employee and click button "Invite";
3.2. Log out as owner;
4. Sign in email employee and confirm the letter "Invite to Mifort Timesheeet";
4.1. Click in letter button "Start using".
![image](https://cloud.githubusercontent.com/assets/25868211/23251137/32f48ae0-f9bd-11e6-93ef-646db8fa138a.png)

**Result:** redirect to a page https://timesheet.mifort.org/login. Not login as employee.
**Expected result:** it needs the support of authorization from different emails.

**Comment by AlexKolonitsky** [comment]
Only google authentication supported for now.
