### ISSUE TITLE
howto deploy the application? (beginner)

### ISSUE THREAD

**Issue by jamalbaharun** [mifort-org/mifort-timesheet#287]
i'm very interested with this app but i dont know how to run the app, after 'npm install' how to serve the app? 
 #thankyou for your answer

**Comment by AndrewRest** [comment]
1) First of all you need MongoDB. 
You can download and install it on your local environment
By default it uses 'mongodb://localhost:27017/homogen' connection url without any credentials.
There is MONGOLAB_URI environment variable responsible for that.

2) Port 
By default It uses 1313 port. There is PORT env variable to set-up any port.

3) At the moment only Google auth is supported.
To use it you need to create in Google development console 2 variables.
Google client ID and Google client Secret.
There are 2 env variables for that GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET.
Also Google auth needs url to return on you application. By default It's http://127.0.0.1:1313/oauth2callback. You need to specify it in your google development console.
Also Mifort Timesheet has env variable for that callback URL: GOOGLE_CALLBACK.

If you do not want to use Google OAuth2 you can use any other authentication strategy.
We use PasspordJS. You can implement any other strategy just you need to change https://github.com/mifort-org/mifort-timesheet/blob/master/backend/libs/authentication.js
