### ISSUE TITLE
Employees: No server request after click on "info"

### ISSUE THREAD

**Issue by DanilchukV** [mifort-org/mifort-timesheet#289]
Chrome 56.0.2924.87 (64-bit); IE 10.0.9200.16660; OS Win 7 Proffessional
**_Steps:_**
1. Open tab "Employees"
2. Click on tab "info"

**_Result:_**
1)Tab "info" does not give any information 2)Tab "Employees" doesn't scroll
![info1_509x260](https://cloud.githubusercontent.com/assets/26150007/23928569/1b2e3034-0929-11e7-9605-27e71ce77ec9.png)

**_Expected result:_** 
For example:
![prokurtka_500x307](https://cloud.githubusercontent.com/assets/26150007/23927900/3f34a674-0925-11e7-806b-f24b46e484f6.png)

**Comment by AlexDormash** [comment]
Нужны цели и текс к ним
