### ISSUE TITLE
Timesheets: weekend should be prefilled with 0 

### ISSUE THREAD

**Issue by AlexKolonitsky** [mifort-org/mifort-timesheet#29]
![default](https://cloud.githubusercontent.com/assets/947428/11841464/831dc2a8-a40e-11e5-9668-026d7366f0c4.PNG)

**Comment by AndrewRest** [comment]
Done. See comit fo #33. Need to disscuss new defaultValues format.

**Comment by AndrewRest** [comment]
Need frontend support. Backend part is done
