### ISSUE TITLE
Tab "Calendar": Not displayed "Days off" into new months list

### ISSUE THREAD

**Issue by DanilchukV** [mifort-org/mifort-timesheet#291]
Chrome 56.0.2924.87 (64-bit); OS Win 7 Proffessional
**_Steps:_**
1. Open tab "Calendar"
2. Click "Show more"
3. Look at the  new list of months

**_Result:_**
Not displayed "Days off" into new months list
![vyihodnyie_747x334](https://cloud.githubusercontent.com/assets/26150007/23928704/f0faaf26-0929-11e7-9d4c-7363dc3c0d8f.png)

**_Expected result:_**
Displayed "Days off" into new months list

**Comment by Czech-nut** [comment]
They are set only for the current year
