### ISSUE TITLE
Project name: Markup is broken when a long name is inputting

### ISSUE THREAD

**Issue by DanilchukV** [mifort-org/mifort-timesheet#296]
Chrome 56.0.2924.87 (64-bit); OS Win 7 Proffessional
**_Steps:_**
1. Open tab "Project"
2. Add new project
3. Edit name of project
4. Input long name (for example: 36 symbols)
5. Save name of project

**_Result;_**
![dlinna imeni_300x124](https://cloud.githubusercontent.com/assets/26150007/23946597/ad97ad56-0983-11e7-8105-ab957f63a118.png)
**_Expected result:_**
Correct displaying of  "Name project" column after inputting a long name

**Comment by AlexKolonitsky** [comment]
waiting page redesign
