### ISSUE TITLE
Tab "Calendar": Hint in the wrong place

### ISSUE THREAD

**Issue by DanilchukV** [mifort-org/mifort-timesheet#299]
Chrome 56.0.2924.87 (64-bit); OS Win 7 Proffessional
**_Steps:_**
1. Open tab "Calendar"
2. Click on tab "Info"
3. Look at the first hint

Result:
![pervaya podskazka_500x286](https://cloud.githubusercontent.com/assets/26150007/23961621/2822a258-09b4-11e7-80ec-2b0efcfb4723.png)
**_Expected result:_**
Suitable hint position

**Comment by JaneKamneva** [comment]
For Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04 this issue isn't reproduced.
