### ISSUE TITLE
Timesheet: No company name

### ISSUE THREAD

**Issue by DanilchukV** [mifort-org/mifort-timesheet#301]
Chrome 56.0.2924.87 (64-bit); OS Win 7 Proffessional
**_Steps:_**
1. Log in as the owner
2. Open tab with name of your company
3. Delete company name
4. Reload the page

**_Result:_**
![kompaniya_502x221](https://cloud.githubusercontent.com/assets/26150007/23968613/20024c96-09cc-11e7-86cc-068a32f9ddd0.png)
**_Expected result:_**
Сompany should have name

**Comment by JaneKamneva** [comment]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04
Actual result:
![selection_011](https://user-images.githubusercontent.com/26093980/28065575-dbad22b4-6641-11e7-94e3-07a34805716e.png)
