### ISSUE TITLE
Tab "Calendar": Add functionality to display default custom days combination

### ISSUE THREAD

**Issue by DanilchukV** [mifort-org/mifort-timesheet#302]
Chrome 56.0.2924.87 (64-bit); OS Win 7 Proffessional
**_Steps:_**
1. Open tab "Calendar"
2. Delete all "Custom Days"
3. Reload the page

**_Result:_**
![vyihodnyie_500x194](https://cloud.githubusercontent.com/assets/26150007/23977739/a5a52180-09f8-11e7-8de3-5a934d142305.png)
**_Expected result:_**
User can change the color day of the week ( i.e : Saturday) by clicking on this day and choosing from the collection of Day Types.

**Comment by AlexKolonitsky** [comment]
Maybe we should prevent user from deleting weekends

**Comment by AlexDormash** [comment]
We also should have default day types for new users (please create separate issue)

**Comment by AlexKolonitsky** [comment]
By default we should have 2 day's types: Holiday, Weekend and user can't delete predefined days.
