### ISSUE TITLE
Tab "Calendar": Users can't create and edit the periods of Company. 

### ISSUE THREAD

**Issue by DanilchukV** [mifort-org/mifort-timesheet#304]
Chrome 56.0.2924.87 (64-bit); OS Win 7 Proffessional
**_Steps:_**
1. Open **Calendar**
2. Click on period splitter 
3. Click on border of any two days 

**_Result:_**
Issue is reproduced for all position (owner; manager; employee)
![17 18_500x279](https://cloud.githubusercontent.com/assets/26150007/23993724/5f7164b0-0a4a-11e7-855e-7ac04459eba0.png)
**_Expected result:_**
User can create and edit the periods of Company. Clicking on period splitter will remove it and merge two periods between it. Click on border of any two days will create the period splitter and split the current period in two.

**Comment by AlexKolonitsky** [comment]
This functionality under construction and probably will be removed

**Comment by JaneKamneva** [comment]
For Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04 **the same problem**.

**Comment by NadiaKolonitskaya** [comment]
Periods can't be edited at calendar but arrows still be available, should the also be removed?

**Comment by Czech-nut** [comment]
We'll replace this functionality
