### ISSUE TITLE
Tab "Projects": No sorting of projects

### ISSUE THREAD

**Issue by DanilchukV** [mifort-org/mifort-timesheet#305]
Chrome 56.0.2924.87 (64-bit); OS Win 7 Proffessional
_**Steps:**_
1. Open **Projects**
2. Add more than 10 projects

**_Result:_**
![sort projects 1_500x502](https://cloud.githubusercontent.com/assets/26150007/24080282/6f0745be-0ca4-11e7-935d-0313219731db.png)
![sort projects 2_500x484](https://cloud.githubusercontent.com/assets/26150007/24080281/6f063066-0ca4-11e7-8e80-d970edd911fd.png)
**_Expected result:_**
Add sorting of projects.

**Comment by JaneKamneva** [comment]
For Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04 everything is ok!
![selection_014](https://user-images.githubusercontent.com/26093980/28068601-f0fd4be6-664e-11e7-96ca-4bff95a2aaaf.png)
