### ISSUE TITLE
Calendar: Blinking colors after some clicks on hexagon

### ISSUE THREAD

**Issue by finDer0** [mifort-org/mifort-timesheet#307]
OS Windows 7 Home Premium; Opera 43.0.2442.1144

**Steps:**
1. Select type of day in calendar (For example: 14 and 28 April 2017 = "Holiday");
2. Click several times on hexagon (color-picker) in "Custom Day" (For example: "Holiday");
3. Click on next hexagon several times (For example: "+").

**Result:** blinking of color-picker and page lag
![bug 2](https://cloud.githubusercontent.com/assets/25868211/24198130/2bf19b06-0f0d-11e7-88a3-ff8f3a579065.gif)

**Expected result:** The image should not blink when the user selects the color of the type day.

**Comment by JaneKamneva** [comment]
For Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04 the problem still available.
