### ISSUE TITLE
Calendar: Forbid input of non-numeric data in field "hours"

### ISSUE THREAD

**Issue by finDer0** [mifort-org/mifort-timesheet#308]
ОS Windows 7 Home Premium; Opera 43.0.2442.1144

**Steps:**
1. Add new type of day in "Custom Day" (For example: "Other");
2. Write any word or phrase in field "hours" (For example: "-15alert!");
3. Choose type of day on calendar (**Pic.1**);

**Result:**
![bug 6 2](https://cloud.githubusercontent.com/assets/25868211/24208986/af002b46-0f2d-11e7-98ac-6afcad51ca01.png)

**Expected result:** It is necessary to limit data entered in field "hours".

**Comment by Nata11ia** [comment]
Cannot be verified because of #345.

**Comment by JaneKamneva** [comment]
For Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04 this problem is still urgent.

**Comment by NickBerilov** [comment]
Cannot replicate on test environment, seems to have already been fixed

**Comment by JaneKamneva** [comment]
For Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04

We still have the problem: user can enter negative number. And also there is an interesting case: user can enter a letter "e" in a "Custom Day", but this letter doesn't displayed!

**See attachment:**
![selection_026](https://user-images.githubusercontent.com/26093980/28166735-c73d5d52-67e1-11e7-8aed-a712d10c442e.png)

**Comment by NickBerilov** [comment]
Reopened as a new issue since the problem is not with non-numeric values anymore
See #361
