### ISSUE TITLE
Tab "Calendar": Necessary to optimize page

### ISSUE THREAD

**Issue by DanilchukV** [mifort-org/mifort-timesheet#309]
Chrome 56.0.2924.87 (64-bit); OS Win 7 Proffessional
_**Steps:**_
1. Open tab "Calendar"
2. Add new colorless  "Custom Days" (e.g. 25)
3. Open tabs promptly: _**Emoloyees --> Calendar**_
4. Reload the page

**_Result:_**
![screenshot_1_503x306](https://cloud.githubusercontent.com/assets/26150007/24317882/9f0b5a10-1105-11e7-88cd-66f1607dd4c8.png)

**_Expected Result_**
Forbid to add more days than colors

**Comment by IrinaAgamyan** [comment]
Why bind amount of day types to amount of colors?

**Comment by anabenko** [comment]
What's the resolution? Forbid or don't bind?
