### ISSUE TITLE
Report: Not highlighted CSV button in "Info"

### ISSUE THREAD

**Issue by finDer0** [mifort-org/mifort-timesheet#311]
ОS Windows 7 Home Premium; Opera 43.0.2442.1144

**Steps:**
1. Open tab "Report";
2. Click on button "Info";
3. Choose the fourth hint.

**Result:** not selected CSV icon.
![bug 1](https://cloud.githubusercontent.com/assets/25868211/24352729/04210968-12eb-11e7-9240-3df0a7c2a067.PNG)

**Expected result:**
It is necessary to highlight the button "CSV", because the "Info" has information about it.

**Comment by Czech-nut** [comment]
It is implemented it new release

**Comment by Nata11ia** [comment]
Verified OS X Chrome 59.0.

**Comment by JaneKamneva** [comment]
For Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04 **everything is ok**.
![selection_016](https://user-images.githubusercontent.com/26093980/28069252-7660750e-6651-11e7-87a4-4e0195dd897f.png)
