### ISSUE TITLE
Timesheet: Changing default value "Time"

### ISSUE THREAD

**Issue by finDer0** [mifort-org/mifort-timesheet#314]
ОS Windows 7 Home Premium; Opera 44.0.2510.857

**Steps:**
1. Create new project in tab "Projects";
2. Open tab "Calendar";
2. Create new type of day and choose hours in "Custom Day" (for example: "Other", hours = 1);
3. Open tab "Timesheet";
4. Click in field "project" and choose the same project (in example "Futurama").

**Result:**
![bug 7](https://cloud.githubusercontent.com/assets/25868211/24695175/02548e24-19e5-11e7-82d5-90069ddcbf12.gif)
_Note_: similar bug in subfield (-).

**Expected result:** the default value should not be changed arbitrarily.

**Comment by JaneKamneva** [comment]
For Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04 **this problem isn't reproduced.**
