### ISSUE TITLE
Long day names overlap with the "delete day" button

### ISSUE THREAD

**Issue by T3G1** [mifort-org/mifort-timesheet#323]
Windows 10, Chrome 57.0.2987.133

**Steps:** 
1. Navigate to the "Calendar" tab
2. Create a new "Day_type" (Type 1)
3. Give it a name that's 48 characters or longer (e.g. "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20")
4. Create a new "Day_type" (Type 2)

**Expected result:**
You can delete Type 2 by clicking the red cross, name for Type 2 is next to its hexagon

**Actual result:**
Type 1's name is displayed on top of the Type 2's red cross, name editing for Type 1 is opened when trying to delete Type 2. The displayed name for Type 2 is also lower than expected
![](https://i.gyazo.com/74b15da2baba3cd7c3e970fb58847568.png)

**Comment by Czech-nut** [comment]
Crashes only if you have spaces between symbols, like in the screenshots above.
