### ISSUE TITLE
Timesheets: Project name was automatically changed and time was set

### ISSUE THREAD

**Issue by Nata11ia** [mifort-org/mifort-timesheet#328]
OS X Chrome 57.0.

Issue us reproduced all the time.

Video is attached: [5.zip](https://github.com/mifort-org/mifort-timesheet/files/920190/5.zip)

**Steps:**
1. Open Timesheets
2. Set Time values one by one without pauses for several days
3. Don't save Time value for next day and click Add button
4. Select Project name
5. Set Time value for project from step 4
6. Delete this value using backspace
7. Type new value
8. Put cursor to Comment field above
9. Put cursor one more Comment field above
![1](https://cloud.githubusercontent.com/assets/23213832/25013632/0831d1dc-207d-11e7-9471-5dd1b47e5b31.png)
10 Reload page
![2](https://cloud.githubusercontent.com/assets/23213832/25013635/0cff933e-207d-11e7-8db8-9c2efece65cf.png)
**Project and Time was changed automatically** for record above!
**Time was automatically changed** for second project for the same day!

**Comment by JaneKamneva** [comment]
For Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04 this issue isn't reproduced.
