### ISSUE TITLE
Tab 'Timesheet': create 'Current week' button

### ISSUE THREAD

**Issue by bakirmanar** [mifort-org/mifort-timesheet#331]
I logged in last time from my home pc 3 months ago. Yesterday I've opened 'timesheets' and it automaticly selected February. Should there be a 'Current week' button which redirects to current week instead of manually turn over to this?

**Comment by AlexKolonitsky** [comment]
What is expected behavior?

**Comment by AlexDormash** [comment]
Делаем пока без дизайна

**Comment by AlexKolonitsky** [comment]
If I am on current period button should not be on the page
