### ISSUE TITLE
"DONE" button functionality

### ISSUE THREAD

**Issue by Czech-nut** [mifort-org/mifort-timesheet#337]
1. Click EDIT on a project, so now you can rename it.
![image](https://user-images.githubusercontent.com/25004670/27643410-a6221ee6-5c29-11e7-9a08-d5c04adadba7.png)
2. Rename it, but don't click DONE and refresh the page
![image](https://user-images.githubusercontent.com/25004670/27644522-755b1814-5c2c-11e7-8906-90fecbd4d5ac.png)
3. The new name is saved, even though the DONE button wasn't pushed.
![image](https://user-images.githubusercontent.com/25004670/27644762-00f4af2a-5c2d-11e7-9562-7a3954662eaf.png)

## Do we really need this button or should we remove it?

**Comment by AlexKolonitsky** [comment]
We should save project only when user clicked "done"
