### ISSUE TITLE
PDF button is not working

### ISSUE THREAD

**Issue by Nata11ia** [mifort-org/mifort-timesheet#344]
http://mifort-timesheet-dev.herokuapp.com/

1. Error when click on PDF link
2. Tooltip is missed
3. PDF step is missed when Info mode is activated

![1](https://user-images.githubusercontent.com/23213832/28020483-4d91bd6e-658d-11e7-9d01-7db7147fb48e.png)

**Console log:**
`reportController.js:140 Uncaught TypeError: Cannot read property 'classList' of undefined
    at local_active (reportController.js:140)
    at HTMLDocument.document.onclick (reportController.js:182)`

**Comment by Czech-nut** [comment]
![image](https://user-images.githubusercontent.com/25004670/28684380-d5d76836-730c-11e7-9557-de3cdd56faf1.png)
