### ISSUE TITLE
The type of the hint is changed after using it at the "Employees" tab

### ISSUE THREAD

**Issue by JaneKamneva** [mifort-org/mifort-timesheet#351]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04

1. Click on tab "Company Name" or "Projects" and reload the page.
2. Press "Info" and click "Next" so many times as possible.
3. Click "Skip".
4. Press "Employees" tab.
5. Click "Info" (**pay attention**: instead of "Skip" button you will see "Done" button! I think it must be fixed!).
6. Press "Next" button and then "Done" button.
7. Switch over the tab "Company Name" or "Projects"
8. Press "Info"

[Video1.mp4.zip](https://github.com/mifort-org/mifort-timesheet/files/1139194/Video1.mp4.zip)

**Actual result:** the type of hint is changed. It is the same as on the "Employees" page. Primary type of the hint will be returned after reloading.

**Expected result:** the hint must be stay unchanged.

**Comment by bakirmanar** [comment]
Fixed by #289

**Comment by JaneKamneva** [comment]
**Everything is ok**
