### ISSUE TITLE
Employees=> Manager cannot invite a new employee

### ISSUE THREAD

**Issue by JaneKamneva** [mifort-org/mifort-timesheet#357]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04

**Steps:**
1. Log in as manager
2. Click "Employees" tab
3. Click the "diamond" button "+"
4. Enter Email of a new Employee 
5. Press "Invite"

**Actual result:** user can see an error message "You have no permission (403 error)" in the lower right corner of the page. Manager cannot invite a new employee. Also there is an error in the console.

**Expected result:** maybe it will be useful to hide "diamond" button for manager!? or if this function must be available for manager, it must be fixed.

**The same problem, when manager tries to delete an Employee (press "x" on the Employee card).**

**See attachment:**
[Video7.mp4.zip](https://github.com/mifort-org/mifort-timesheet/files/1142490/Video7.mp4.zip)

**Comment by JaneKamneva** [comment]
Also the same question on the "Calendar" page: when Manager adding a new "Custom Day" or changing the type of the day on the calendar, there is an error message  "You have no permission (403 error)" and an error in the console. Maybe these functions must be hidden for manager?

**Comment by Czech-nut** [comment]
Andrey Koyro must have some ideas
And also [this](https://github.com/mifort-org/mifort-timesheet/issues/431) happens only to the Manager and 403 error (No Permission) appears
