### ISSUE TITLE
Employee=>Doesn't work "Info"

### ISSUE THREAD

**Issue by JaneKamneva** [mifort-org/mifort-timesheet#360]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04

1. click on "Employee" tab
2.  click on "Info"

**Actual result:** nothing has happened. 
**Expected result:** user has to see a hint like this:
![selection_025](https://user-images.githubusercontent.com/26093980/28164157-b2265f64-67d6-11e7-8986-ef6cb5c9dc69.png)

**Comment by Czech-nut** [comment]
#289
