### ISSUE TITLE
Projects=> Maybe it will be useful to establish some limits in the field "Project name"

### ISSUE THREAD

**Issue by JaneKamneva** [mifort-org/mifort-timesheet#363]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04

**Actual result:" user can enter extra long data.
**See attachment:**
![selection_027](https://user-images.githubusercontent.com/26093980/28169782-0c562784-67ec-11e7-944c-b25c20185678.png)

**Comment by AlexKolonitsky** [comment]
Agree, project name shouldn't be more then 140 symbols

**Comment by JaneKamneva** [comment]
**Everything is ok**
