### ISSUE TITLE
Projects=>A very long Email overlaps the icon "chevron-down" 

### ISSUE THREAD

**Issue by JaneKamneva** [mifort-org/mifort-timesheet#364]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04

**Steps:**
1. Log in as the owner
2. Invite a user with long Email address
3. Click on "Projects"
4. Click on "chevron-down" icon and choose a user with long Email address

**Actual result:** very long Email of the Employee overlaps the icon "chevron-down" .
**Expected result:** long Email doesn't overlap the "chevron-down" icon. 
**See attachment:**
![selection_028](https://user-images.githubusercontent.com/26093980/28172969-bce407de-67f5-11e7-97b6-7646ff0cb180.png)

**Comment by AlexKolonitsky** [comment]
Waiting for projects page redesign

**Comment by JaneKamneva** [comment]
**ok**
