### ISSUE TITLE
Projects=>Wrong adapting of the numbers

### ISSUE THREAD

**Issue by JaneKamneva** [mifort-org/mifort-timesheet#365]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04

**Steps:**
1. Click on "Projects" tab
2. Create a New Project
3. Choose Email address
4. In the field "Workload" enter: .1
5. Reload the page 

**Actual result:** in the field "Workload" user can still see: .1 
**Expected result:**maybe it will be better to adapt automatically to such form: 0.1? Cause the automatic adapting is happened when user at first clicks on this field with data: .1 and then on another field.
**See attachment:**
[Video9.mp4.zip](https://github.com/mifort-org/mifort-timesheet/files/1145708/Video9.mp4.zip)

**Comment by JaneKamneva** [comment]
**Everything is ok**

**Comment by anabenko** [comment]
FF 55.0.3
role: owner
Dev/Prod - fixed
