### ISSUE TITLE
Report=> Error in the console (Click Project=>press filter "Project Name")

### ISSUE THREAD

**Issue by JaneKamneva** [mifort-org/mifort-timesheet#369]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04

**Steps:**
1. Click on "Report" tab 
2. Press  "Project" 
3. Press Filter in the field "Project Name"

**Actual result:** an error in the console. **The same problem: Report=> Employee=> field "Employee Name" and Report=> Project&Employee=> fields "Project Name", "Employee Name"**
![selection_031](https://user-images.githubusercontent.com/26093980/28219432-994baac8-68c4-11e7-9b43-289c4d122d42.png)

**Expected result:** no errors in the console.

**Comment by IrinaAgamyan** [comment]
fixed in #413

**Comment by JaneKamneva** [comment]
**Everything is ok**
