### ISSUE TITLE
Projects=> the same project names when adding new  projects very quickly

### ISSUE THREAD

**Issue by JaneKamneva** [mifort-org/mifort-timesheet#371]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04

**Steps:**
1. Open "Projects" page
2. Very quickly press several times "diamond" button or "Add Project"

**Actual result:** projects have the same names
**Expected result:** the number of next project must be greater than previous one 

**See attachment:** 
![selection_034](https://user-images.githubusercontent.com/26093980/28265102-c07c710c-6af6-11e7-9490-c4eaf970788c.png)

**Comment by IrinaAgamyan** [comment]
Fixed in #373

**Comment by JaneKamneva** [comment]
**Problem is still available**

**Comment by JaneKamneva** [comment]
**Everything is ok**
