### ISSUE TITLE
Employee Lifecycle: redirect to the week of the report

### ISSUE THREAD

**Issue by Czech-nut** [mifort-org/mifort-timesheet#372]
## Current result:
When manager clicks on the report (in order to approve or reject) - manager is redirected to the page with the current week.
## Expected result:
Manager should be redirected to the week for which the report was done.

**Comment by anabenko** [comment]
How to click on the report?

**Comment by Czech-nut** [comment]
@anabenko Please, don't test issues with label "Lifecycle" - this functionality is not finished, so we've hidden it. It will be available in a new release (in about 2 weeks)
