### ISSUE TITLE
Delete the company=>Error in the console

### ISSUE THREAD

**Issue by JaneKamneva** [mifort-org/mifort-timesheet#375]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04
**You must have a previously created company.**
**Steps:**
1. Log in as the owner
2. Click on "Company Name" tab
3. Click on "trash" button
4. Press " Delete"

**Actual result:** there is an error in the console
> angular.js:10967 GET http://mifort-timesheet-dev.herokuapp.com/api/v1/user 401 (Unauthorized)

**See attachment:** ![_002](https://user-images.githubusercontent.com/26093980/28310966-cbeeb94e-6bb6-11e7-8a82-0e82e5d285b4.png)
﻿**Expected result:** no errors.

​

**Comment by bakirmanar** [comment]
Waiting for implentation of Multiaccounts

**Comment by anabenko** [comment]
win 7, FF 55.0.3
role: owner
Dev/Prod - Fixed
