### ISSUE TITLE
Timesheet=> The sum of all hours of one project in one day more than 24.00 hours

### ISSUE THREAD

**Issue by JaneKamneva** [mifort-org/mifort-timesheet#378]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04

**Steps:**
1. Click "Timesheet" tab
2. Choose any date and press several times "+" button in order to add more projects  for this day
3. Enter hours which sum more then 24

**Actuall result:**  the application allows to do it. It is a logic mistake.
**Expected result:** the sum of all working hours of one day cannot be more than 24.
**See attachment:**
![selection_002](https://user-images.githubusercontent.com/26093980/28363988-5b1b5120-6c8b-11e7-8e72-15fa07de8d99.png)

**Comment by AlexKolonitsky** [comment]
Warn person that he has more then 8h (yellow), 16h (orange), 24h (red) at that day, but don't limit input

**Comment by AlexKolonitsky** [comment]
@Czech-nut warning visible short period of time and it is better to highlight such errors in table, we need better design for this issue
