### ISSUE TITLE
Timesheet=>field Comment. User can enter an extra long data

### ISSUE THREAD

**Issue by JaneKamneva** [mifort-org/mifort-timesheet#380]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04

1. Enter extra long data in the field "Comment"

**Actual result:**  user can enter an extra long data. And the visual presentation of current data isn't good, cause there is a single-line field.
**See attachment:** 
[video3.mp4.zip](https://github.com/mifort-org/mifort-timesheet/files/1158930/video3.mp4.zip)
**Expected result:** maybe it will be useful to establish some limit?! And as for my mind this fild must be multiline one.

**Comment by AlexKolonitsky** [comment]
let't limit it with 1000 symbols

**Comment by JaneKamneva** [comment]
**Everything is ok but see #421**

**Comment by NadiaKolonitskaya** [comment]
It is only 140 symbols now, is that correct?

**Comment by Czech-nut** [comment]
@NadiaKolonitskaya Yes, the limit is 140 symbols per line, but we should warn user that he is not able to input any data any more when he has reached the limit
