### ISSUE TITLE
Why in .csv file there is "CEO" in the column "Role" (although it is only an Employee)  

### ISSUE THREAD

**Issue by JaneKamneva** [mifort-org/mifort-timesheet#389]
**Steps:**
1. Log in as the owner
2. Invite an Employee and add him in "Project"
3. Log out
4. Log in as before invited Employee
5. Fill in Timesheet
6. Click on "Report" tab, CSV
7. Open .csv file

**Actual result:** user can  see in the column "Role" - > "CEO". **Is it ok?**
![selection_008](https://user-images.githubusercontent.com/26093980/28418443-617a2f76-6d64-11e7-92f2-5e977515f895.png)

**Comment by anabenko** [comment]
win 7, FF 55.0.3
role: employee
Dev/Prod - Fixed. Role column removed.
