### ISSUE TITLE
Lifecycle: "Ready for Approve" doesn't work

### ISSUE THREAD

**Issue by Czech-nut** [mifort-org/mifort-timesheet#393]
1. Fill your timesheet as an Employee
2. Press "Ready for Approve" 
3. You can't do it
![image](https://user-images.githubusercontent.com/25004670/28457004-0dfd879a-6e0d-11e7-8b23-947de160e90a.png)

**Comment by JaneKamneva** [comment]
Chrome v. 58.0.3029.110 (64-bit), Opera v. 45.0, FF v. 53.0.2 (64-bit);
OS: Linux Ubuntu 14.04

This problem is available for Manager and Owner

**Comment by JaneKamneva** [comment]
**Maybe it will be useful to block ability to "Approve" timesheets, which are in the future.**

**Comment by anabenko** [comment]
FF 55.0.3
role: employee
Dev - "Ready for Approve" removed.
Fixed?
