### ISSUE TITLE
Report: tabs don't work

### ISSUE THREAD

**Issue by Czech-nut** [mifort-org/mifort-timesheet#413]
![image](https://user-images.githubusercontent.com/25004670/28620362-477ac9d6-7215-11e7-85ea-371d37d8f91d.png)
![image](https://user-images.githubusercontent.com/25004670/28620375-532a9b76-7215-11e7-9360-5fbf71c650a7.png)
![image](https://user-images.githubusercontent.com/25004670/28620387-5fb69e94-7215-11e7-8310-7492ba8a670b.png)
![image](https://user-images.githubusercontent.com/25004670/28620399-69587378-7215-11e7-9006-c44e95b8e17a.png)

**Comment by Czech-nut** [comment]
After clicks on different tabs it stops working

**Comment by JaneKamneva** [comment]
**Everything is ok**
