### ISSUE TITLE
Add limits to Weekly timelog

### ISSUE THREAD

**Issue by Czech-nut** [mifort-org/mifort-timesheet#415]
Maximum per week is 168 hours (24*7=168)
![image](https://user-images.githubusercontent.com/25004670/28634106-d3dd1748-723e-11e7-9c05-18679e83fd67.png)

**Comment by AlexKolonitsky** [comment]
Add project assignment limit to 24h, warn user in case he put more then 8h per assignment, and warn user if one person has more then 16h per day across all his assignments

**Comment by anabenko** [comment]
FF 55.0.3
Dev/Prod - fixed
