### ISSUE TITLE
Employee=>Timesheet isn't available

### ISSUE THREAD

**Issue by JaneKamneva** [mifort-org/mifort-timesheet#416]
**Steps:**
1. Log in as manager
2. Add a new employee by email (ykamneva@objectstyle.com) to the existing project
3. Then log in as an Employee 
**Actual result:** Timesheet isn't available. An Employee can see that the page is loading, but nothing is being happened..
![selection_045](https://user-images.githubusercontent.com/26093980/28676220-c5b76f60-72f2-11e7-8539-ea978c69289e.png)
**Expected result:** timesheet must be available.

**Comment by Nata11ia** [comment]
Projects were set. Please note that manager does not see First and Last Name:

![1](https://user-images.githubusercontent.com/23213832/28678711-bad18cd2-72f9-11e7-822e-34f9a99cbe74.png)

**Comment by AlexKolonitsky** [comment]
Multi company issue, will be fixed in next version
