### ISSUE TITLE
Project column resizing don't work properly 

### ISSUE THREAD

**Issue by AlexKolonitsky** [mifort-org/mifort-timesheet#419]
![2017-07-31_15h48_06](https://user-images.githubusercontent.com/947428/28778431-dcfddfc0-7607-11e7-85b8-7ddc6b4ad06b.png)

**Comment by anabenko** [comment]
win 7, FF 55.0.3
role: owner
dev

Not Fixed. 
Column is not resizable.  
Default length appears to be shorter then on attached (in description) screenshot
![len](https://user-images.githubusercontent.com/25684329/30058719-7ad52258-923c-11e7-9e9e-67c372334f37.png)
