### ISSUE TITLE
Counting of decimal numbers

### ISSUE THREAD

**Issue by Czech-nut** [mifort-org/mifort-timesheet#425]
1. Assign any decimal number to **yourself** for a project
![image](https://user-images.githubusercontent.com/25004670/28971878-591869f0-7936-11e7-86d0-d531e106c57e.png)
2. Go to your timesheet and have a look at the expected time
![image](https://user-images.githubusercontent.com/25004670/28972022-d07c84ea-7936-11e7-8df4-5e6144476633.png)

**Actual result**:
Time is counting as in JavaScript.

**Expected result**:
Show actual decimal number (for example 0.2 in this case).

**Comment by anabenko** [comment]
win 7, FF 55.0.3
role: owner
dev

Fixed
