### ISSUE TITLE
2 scrolls on a small screen

### ISSUE THREAD

**Issue by Czech-nut** [mifort-org/mifort-timesheet#427]
**Display:**
FHD (1920 x 1080)
**Dimension:**
(mm) : 384 x 265 x 24.6
(inches) : 15.12" x 10.43" x 0.97"

![pasted image at 2017_08_11 03_35 pm](https://user-images.githubusercontent.com/25004670/29213532-4ab672d2-7eac-11e7-848b-cfeca9205be7.png)

**Comment by anabenko** [comment]
FHD (1920 x 1080)
Dev - Fixed.
