### ISSUE TITLE
Calendar: Page Redesign

### ISSUE THREAD

**Issue by Czech-nut** [mifort-org/mifort-timesheet#429]
![calendar-report](https://user-images.githubusercontent.com/25004670/29282467-92ca1638-812b-11e7-9d76-0388e01e169b.png)

https://drive.google.com/drive/folders/0B4a3uMjfh54pZ2NZTjY2TUc0TlU

**Comment by AndrewRest** [comment]
1) Reduce custom periods. We do not need it as array in project/company entities
2) Intoduce new period field - weekly, monthly and amount - integer.
3) Change UI - remove splitters, add block with common period (see mockup).

**Comment by anabenko** [comment]
win 7, ff 55.0.3
role: onwer
dev


    Reduce custom periods. We do not need it as array in project/company entities - Don't understand what that means?
    Intoduce new period field - weekly, monthly and amount - integer. - not fixed.  Period field is missing
    Change UI - remove splitters, add block with common period (see mockup). - Fixed.  Splitters are removed.
