### ISSUE TITLE
Calendar: 'Show more' button redirects to Timesheet page

### ISSUE THREAD

**Issue by Czech-nut** [mifort-org/mifort-timesheet#431]
Press 'Show more' button
![image](https://user-images.githubusercontent.com/25004670/29310944-716d8ece-81b8-11e7-82bc-847325517e9f.png)

*Actual result:*
1. Loading slowly
![image](https://user-images.githubusercontent.com/25004670/29310990-aae90a98-81b8-11e7-968f-76e8d4744237.png)
2. Redirects to Timesheet Page
![image](https://user-images.githubusercontent.com/25004670/29311034-db0d851e-81b8-11e7-88d4-f0a4945810c8.png)

*Expected result:*
It should show more months in Calendar

**Comment by anabenko** [comment]
FF 55.0.3
role: Manager
Dev - not fixed.
