### ISSUE TITLE
Projects: Project name field behavior is inconsistent with other inputs

### ISSUE THREAD

**Issue by antonxt** [mifort-org/mifort-timesheet#434]
The **Project Name input** appears after "edit" link clicked, and to save the changes the user must click on "Done". This is inconsistent with other text inputs, which save the changes when they loose focus. It is counter-intuitive and the user may forget to click "Done", which happened to me.

Alternatively, the form can have edit/save feature to prevent unintended edits, but it should be done so that:
- It prompts the user to save changes if they leave without clicking "done".
- The look of the input should be more distinct to point out its state.
- The list of employees and their workload should also be in that form, i.e. by default they should not be editable.

<img width="420" alt="screen shot 2" src="https://user-images.githubusercontent.com/7406247/29605673-7d9aa9e2-87f4-11e7-897b-a264b649af68.png">

**Comment by AlexKolonitsky** [comment]
Waiting Projects page redesign

**Comment by margaritamikulionok** [comment]
it will be fixed in new design
