### ISSUE TITLE
Projects: A new project should not be saved until the user made any changes

### ISSUE THREAD

**Issue by antonxt** [mifort-org/mifort-timesheet#435]
The new project is added to the list right after "Plus" icon is clicked. Then, if no changes were made, it stays in the middle of the list forever. It makes the list longer and cluttered with fake projects.

Expected: store the new project only after it was explicitly saved by the user.
A simpler temporary workaround: show "New projects" first in the list, so they are not forgotten and eventually are edited and used.

The actual look of our list of projects:
<img width="945" alt="screen shot 3" src="https://user-images.githubusercontent.com/7406247/29606657-8e6711ae-87f7-11e7-967a-20aab19d87d7.png">

**Comment by Czech-nut** [comment]
@antonxt A new project is now saved only after you press "Done" button
and new projects are displayed in the beginning of the projects' list

**Comment by Czech-nut** [comment]
@antonxt 
1. A new project is now saved only after you press "Done" button
2. New projects are displayed in the beginning of the projects' list
3. After saving a new project - it stands in the alphabetical order
