### ISSUE TITLE
Calendar: Change UI - remove splitters, add block with common period (see mockup)

### ISSUE THREAD

**Issue by Czech-nut** [mifort-org/mifort-timesheet#439]
![calendar-report](https://user-images.githubusercontent.com/25004670/29282467-92ca1638-812b-11e7-9d76-0388e01e169b.png)

**Comment by anabenko** [comment]
win 7, FF 55.0.3
role: owner, manager
dev

**Screenshot attached is not a mockup, right?**

Issue is fixed. Splitters removed, common periods are displayed
![ff](https://user-images.githubusercontent.com/25684329/30056718-175558b8-9234-11e7-89d0-6e64f098247e.png)
