### ISSUE TITLE
UI issues: Report page

### ISSUE THREAD

**Issue by AndrewRest** [mifort-org/mifort-timesheet#44]
1) Space between filter names (Project Name, User Name)
![image](https://cloud.githubusercontent.com/assets/12434689/12014874/e02ecad4-ad44-11e5-99e4-48974d998953.png)

2) Time field - big letter
![image](https://cloud.githubusercontent.com/assets/12434689/12014885/120c73c6-ad45-11e5-854c-5160fb3eeb3c.png)

3) Page number align
![image](https://cloud.githubusercontent.com/assets/12434689/12014892/2db98ba4-ad45-11e5-97d1-84e0fbf78117.png)

4) Filter icon should be blue only if filteris selected
![image](https://cloud.githubusercontent.com/assets/12434689/12014986/a1229936-ad46-11e5-9ee8-6d6c3ab4215c.png)

5) The smallest number of filter row value should be > 10
I think 5 is not usefull

**Comment by altrofimov** [comment]
5 - agree
