### ISSUE TITLE
Timesheet tab: comments field length extension

### ISSUE THREAD

**Issue by anabenko** [mifort-org/mifort-timesheet#441]
role: employee (ownerownerq@gmail.com/galadali)
dev/prod
Win 7, FF 55.0.3

Comment field is rather short.  I had the need to insert longer text, but couldn't

**Comment by Czech-nut** [comment]
Input size is limited to 1000 symbols purposely. It's better to log smaller tasks in comments. If the user wants to input a lot of tasks - he/she should add them in different lines.

**Comment by anabenko** [comment]
win 7, FF 55.0.3
role: owner
dev 

Current input length is 140 characters.  1000 would have been more then enough.
