### ISSUE TITLE
Projects: narrow project name edit field

### ISSUE THREAD

**Issue by anabenko** [mifort-org/mifort-timesheet#446]
win 7, FF 55.0.3
role: owner
dev/prod

Open Projects page
Click to Edit project name
-> edit field is a bit narrow
![2017-09-04_1141](https://user-images.githubusercontent.com/25684329/30018850-c385e674-915e-11e7-8ddd-c34942c07ff5.png)

Same with Company Name field

**Comment by margaritamikulionok** [comment]
it will be fixed in new design
