### ISSUE TITLE
Report: 'Back to Report' redirects to Employees Report page

### ISSUE THREAD

**Issue by anabenko** [mifort-org/mifort-timesheet#462]
win 7, FF 55.0.3
role: manager, owner
dev

1. Open Report page
2. Click on any Empl Name
3. Corresponding timesheet is displayed. Click Back to Report button
-> Employees Report page is opened.
I would prefer to return to the page I came from (Reports)

**Comment by anabenko** [comment]
Button 'Back to Report' is renamed to 'Back to Employees Report'
Now it's confusing. Since we came from Report page (not Employees Report page, which also exists).

As i understand it, if we came from Report page, button should be named 'Back to Report', and return user to Report page
If we came from Employees report, button should be 'Back to Employees Report' and return user to Employees Report page.

Not fixed.

**Comment by AlexDormash** [comment]
fix

**Comment by anabenko** [comment]
win 7, FF 55.0.3
role: owner
dev - Fixed
