### ISSUE TITLE
Timesheet: Project name items

### ISSUE THREAD

**Issue by anabenko** [mifort-org/mifort-timesheet#464]
Once Timesheet tab is opened. Left hand side menu is expanded with Project names. 
Items are clickable, but nothing happens.  
Should there be some action or not?

**Comment by Czech-nut** [comment]
These items should not be clickable
![image](https://user-images.githubusercontent.com/25004670/30054640-6051dd7e-9235-11e7-8dbc-e09d141eb2a0.png)
