### ISSUE TITLE
Timesheeets page not loading

### ISSUE THREAD

**Issue by anabenko** [mifort-org/mifort-timesheet#474]
win 7, FF 55.0.3
role: owner
dev

1. Create new project. Invite employees.
2. Open Timesheets page
-> error in console.  Page hangs Loading..
Error: blockday[2] is undefined
blockTable@http://mifort-timesheet-dev.herokuapp.com/timesheet/timesheetController.js:167:24
$scope.init/<@http://mifort-timesheet-dev.herokuapp.com/timesheet/timesheetController.js:209:21
f/<@http://mifort-timesheet-dev.herokuapp.com/bower_components/angular/angular.min.js:119:221
$eval@http://mifort-timesheet-dev.herokuapp.com/bower_components/angular/angular.min.js:133:442
$digest@http://mifort-timesheet-dev.herokuapp.com/bower_components/angular/angular.min.js:131:33
$apply@http://mifort-timesheet-dev.herokuapp.com/bower_components/angular/angular.min.js:134:234
g@http://mifort-timesheet-dev.herokuapp.com/bower_components/angular/angular.min.js:88:1
R@http://mifort-timesheet-dev.herokuapp.com/bower_components/angular/angular.min.js:92:116
Zf/</v.onload@http://mifort-timesheet-dev.herokuapp.com/bower_components/angular/angular.min.js:93:155
  angular.js:12722:17

**Comment by Czech-nut** [comment]
@anabenko Could you please give more details, we can't reproduce

**Comment by AndrewRest** [comment]
Looks like It's duplicate for #498
