### ISSUE TITLE
Timesheet:logged information disappeared

### ISSUE THREAD

**Issue by margaritamikulionok** [mifort-org/mifort-timesheet#516]
![screenshot_5](https://user-images.githubusercontent.com/33221440/33607492-5c40e42a-d9d2-11e7-8281-bd03ddf09550.png)
![screenshot_3](https://user-images.githubusercontent.com/33221440/33607496-5d51ff48-d9d2-11e7-8d63-9a5a477c6c17.png)
![screenshot_4](https://user-images.githubusercontent.com/33221440/33607499-5f70a8d8-d9d2-11e7-8837-7529150a549e.png)

**Comment by AndrewRest** [comment]
There is 2 reason why it can happend
1) Project was archived
2) Timeout aproach for saving (#529 )

**Comment by AndrewRest** [comment]
Close an issue as duplicate for too previous
