### ISSUE TITLE
mifort. not working menu

### ISSUE THREAD

**Issue by shapet** [mifort-org/mifort-timesheet#525]
Steps to reproduce:

1. open http://mifort.org
2. click on the drop-down menu GAME DEV
3. scroll down the page
4. click menu item

Expected result:
moved to the selected menu item

Actual result:
not working menu
![1](https://user-images.githubusercontent.com/36628611/36443710-94e62ca0-168a-11e8-8c72-a71211c02cfa.jpg)

**Comment by AndrewRest** [comment]
It's Mifort timesheet issues. Not related to Mifort site at all
