### ISSUE TITLE
mifort. non working link

### ISSUE THREAD

**Issue by shapet** [mifort-org/mifort-timesheet#526]
Steps to reproduce:

1. open http://mifort.org

2. click on the drop-down menu E-LEARNING PLATFORM

3. scroll down the page

4. click menu item  Game Dev

Expected result:
moved to the selected menu item

Actual result:
Error 404 The requested URL /portfolio/portfolio/game-dev.html was not found on this server.

![2](https://user-images.githubusercontent.com/36628611/36444434-784d38ca-168c-11e8-93ab-54c08e422bba.jpg)

**Comment by AndrewRest** [comment]
It's Mifort timesheet issues. Not related to Mifort site at all
