### ISSUE TITLE
Triple screen flashing

### ISSUE THREAD

**Issue by AndrewRest** [mifort-org/mifort-timesheet#53]
Pre-conditions:
User should be logouted from system

Steps:
1) Log in

Actual result: Waiter -> Menu + login form -> Menu + Timesheet (login form is replaced by timesheet)
Expected result: Waiter -> Full loaded page

**Comment by altrofimov** [comment]
1 more fals to be removed

**Comment by altrofimov** [comment]
Seems to be fixed/
