### ISSUE TITLE
No "availablePositions" for new projects

### ISSUE THREAD

**Issue by altrofimov** [mifort-org/mifort-timesheet#79]

**Comment by altrofimov** [comment]
_id: "56b98987c99fe0e4380a6aa8"
active: true


availablePositions: null


companyId: "56b98175c99fe0e4380a6a73"
createdOn: "2016-02-09T06:39:03.797Z"
dayTypes: [{name: "Weekend", time: 0, color: "#c5e9fb"}, {name: "Corporate", time: 0, color: "#f3cce1"},…]
defaultValues: [{date: "02/02/2016"}, {date: "01/02/2016"}]
name: "New Project"
periods: [{start: "12/31/2014", end: "01/30/2015"}, {start: "01/31/2015", end: "02/27/2015"},…]
template: {date: "", role: "", time: 4, comment: ""}
updatedOn: "2016-02-09T06:39:03.797Z"

**Comment by altrofimov** [comment]
Still reproducible

**Comment by altrofimov** [comment]
'СEO' in DEFAULT_AVAILABLE_POSITIONS has russian "C" :)

**Comment by AndrewRest** [comment]
Fixed. Make any update for your company to see the fix
