### ISSUE TITLE
Removing the hashtag from AngularJS urls (# symbol)

### ISSUE THREAD

**Issue by AlexKolonitsky** [mifort-org/mifort-timesheet#87]
http://stackoverflow.com/questions/14771091/removing-the-hashtag-from-angularjs-urls-symbol

**Comment by altrofimov** [comment]
We need new link for login:

app.get('/login', function (req, res, next) {
        passport.authenticate('google',

**Comment by AndrewRest** [comment]
new login URL /googlelogin

**Comment by altrofimov** [comment]
All working good except the refreshing pages.
(https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode)
